export const apiUrl = process.env.NODE_END !== 'production' ? 'http://localhost:5000/api' : ''
export const LOCAL_STORAGE_TOKEN_NAME = 'learnit-mern'
export const POST_LOADED_SUCCESS = 'POST_LOADED_SUCCESS'
export const POST_LOADED_FAILED = 'POST_LOADED_FAILED'
export const SET_AUTH = 'SET_AUTH'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const FIND_POST = 'FIND_POST'
